name: eastbus_trip_management_app
description: EastBus.lk Trip Management App for authorised drivers and conductors.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # Laravel REST API
  http: ^1.2.2

  # Login / Session Storage
  shared_preferences: ^2.3.2

  # GPS / Live Tracking
  geolocator: ^13.0.1

  # OpenStreetMap
  flutter_map: ^8.2.2
  latlong2: ^0.9.1

  # Passenger QR Scanner
  mobile_scanner: ^6.0.2

  # Date / Time
  intl: ^0.19.0

  # Firebase
  firebase_core: ^4.1.0
  firebase_database: ^12.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3
  flutter_native_splash: ^2.4.4

flutter:
  uses-material-design: true

  assets:
    - assets/eastbus_logo.png

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/eastbus_logo.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/eastbus_logo.png"
  min_sdk_android: 21
  remove_alpha_ios: true

flutter_native_splash:
  color: "#FFFFFF"
  image: "assets/eastbus_logo.png"

  android: true
  ios: true
  web: true

  android_12:
    color: "#FFFFFF"
    image: "assets/eastbus_logo.png"
    icon_background_color: "#FFFFFF"