<?php
namespace App\Http\Controllers\Api;
use App\Http\Controllers\Controller;use Illuminate\Http\Request;use Illuminate\Support\Facades\DB;use Illuminate\Validation\ValidationException;
class TripStaffController extends Controller {
 private function staff(Request $r){return $r->attributes->get('staff');}
 private function assigned($staff,$tripId){return DB::table('trips')->where('id',$tripId)->where('operator_id',$staff->operator_id)->where(function($q)use($staff){$q->where('driver_id',$staff->id)->orWhere('conductor_id',$staff->id);})->first();}
 public function dashboard(Request $r){$s=$this->staff($r);$today=now()->toDateString();$ids=DB::table('trips')->where('operator_id',$s->operator_id)->where(function($q)use($s){$q->where('driver_id',$s->id)->orWhere('conductor_id',$s->id);})->whereDate('service_date',$today)->pluck('id');$active=DB::table('trips')->join('routes','routes.id','=','trips.route_id')->join('buses','buses.id','=','trips.bus_id')->whereIn('trips.id',$ids)->where('trips.status','active')->select('trips.*','routes.origin','routes.destination','buses.bus_number')->first();$passengers=DB::table('bookings')->whereIn('trip_id',$ids)->where('status','confirmed')->sum('passenger_count');$checked=DB::table('booking_passengers')->join('bookings','bookings.id','=','booking_passengers.booking_id')->whereIn('bookings.trip_id',$ids)->whereNotNull('booking_passengers.checked_in_at')->count();unset($s->password);return ['success'=>true,'staff'=>$s,'stats'=>['today_trips'=>$ids->count(),'passengers'=>(int)$passengers,'checked_in'=>$checked],'active_trip'=>$active];}
 public function trips(Request $r){$s=$this->staff($r);$rows=DB::table('trips')->join('routes','routes.id','=','trips.route_id')->join('buses','buses.id','=','trips.bus_id')->where('trips.operator_id',$s->operator_id)->where(function($q)use($s){$q->where('trips.driver_id',$s->id)->orWhere('trips.conductor_id',$s->id);})->whereDate('trips.service_date','>=',now()->subDay()->toDateString())->orderBy('trips.service_date')->orderBy('trips.departure_time')->select('trips.*','routes.name as route_name','routes.origin','routes.destination','buses.bus_number','buses.bus_name','buses.seat_count')->get();foreach($rows as $x){$x->booked_passengers=(int)DB::table('bookings')->where('trip_id',$x->id)->where('status','confirmed')->sum('passenger_count');}return ['success'=>true,'trips'=>$rows];}
 public function start(Request $r,$id){$s=$this->staff($r);$t=$this->assigned($s,$id);if(!$t)return response()->json(['success'=>false,'message'=>'Trip is not assigned to this staff member.'],403);if($t->status!=='scheduled')return response()->json(['success'=>false,'message'=>'Only a scheduled trip can be started.'],422);DB::table('trips')->where('id',$id)->update(['status'=>'active','started_at'=>now(),'updated_at'=>now()]);return ['success'=>true,'message'=>'Trip started.'];}
 public function end(Request $r,$id){$s=$this->staff($r);$t=$this->assigned($s,$id);if(!$t)return response()->json(['success'=>false,'message'=>'Trip is not assigned to this staff member.'],403);if($t->status!=='active')return response()->json(['success'=>false,'message'=>'Only an active trip can be ended.'],422);DB::table('trips')->where('id',$id)->update(['status'=>'completed','ended_at'=>now(),'updated_at'=>now()]);DB::table('bookings')->where('trip_id',$id)->where('status','confirmed')->update(['status'=>'completed','updated_at'=>now()]);return ['success'=>true,'message'=>'Trip completed.'];}
 public function location(Request $r,$id){$s=$this->staff($r);$t=$this->assigned($s,$id);if(!$t||$t->status!=='active')return response()->json(['success'=>false,'message'=>'Live location is accepted only for an assigned active trip.'],422);$v=$r->validate(['latitude'=>'required|numeric|between:-90,90','longitude'=>'required|numeric|between:-180,180','speed_kmh'=>'nullable|numeric|min:0']);DB::table('live_locations')->insert(['trip_id'=>$id,'latitude'=>$v['latitude'],'longitude'=>$v['longitude'],'speed_kmh'=>$v['speed_kmh']??null,'recorded_at'=>now()]);return ['success'=>true];}
 public function passengers(Request $r,$id){$s=$this->staff($r);if(!$this->assigned($s,$id))return response()->json(['success'=>false,'message'=>'Trip is not assigned to you.'],403);$rows=DB::table('booking_passengers')->join('bookings','bookings.id','=','booking_passengers.booking_id')->where('bookings.trip_id',$id)->whereIn('bookings.status',['confirmed','completed'])->select('booking_passengers.passenger_name','booking_passengers.nic','booking_passengers.seat_number','booking_passengers.checked_in_at','bookings.booking_reference')->orderBy('booking_passengers.seat_number')->get()->map(function($x){$x->checked_in=$x->checked_in_at!==null;return $x;});return ['success'=>true,'passengers'=>$rows];}
 public function notifications(Request $r){$s=$this->staff($r);$rows=DB::table('notifications')->where(function($q)use($s){$q->where('target_type','all')->orWhere('target_type','operators')->orWhere(function($x)use($s){$x->where('target_type','operator')->where('operator_id',$s->operator_id);});})->latest('id')->limit(100)->get();return ['success'=>true,'notifications'=>$rows];}
 public function emergency(Request $r,$id){$s=$this->staff($r);$t=$this->assigned($s,$id);if(!$t)return response()->json(['success'=>false,'message'=>'Trip is not assigned to you.'],403);$v=$r->validate(['latitude'=>'nullable|numeric','longitude'=>'nullable|numeric','message'=>'nullable|string|max:1000']);DB::table('emergency_alerts')->insert(['operator_id'=>$s->operator_id,'trip_id'=>$id,'staff_id'=>$s->id,'message'=>$v['message']??'Emergency alert','latitude'=>$v['latitude']??null,'longitude'=>$v['longitude']??null,'status'=>'open','created_at'=>now(),'updated_at'=>now()]);return ['success'=>true,'message'=>'Emergency alert sent.'];}
 public function verifyTicket(Request $r){$s=$this->staff($r);$code=$r->validate(['ticket_code'=>'required|string|max:255'])['ticket_code'];$row=$this->ticketRow($s,$code);if(!$row)return response()->json(['success'=>false,'message'=>'Invalid ticket or ticket does not belong to your assigned trip.'],404);if($row->ticket_status==='cancelled'||$row->booking_status==='cancelled')return response()->json(['success'=>false,'message'=>'This ticket has been cancelled.'],422);return ['success'=>true,'ticket'=>$this->ticketPayload($row)];}
 public function checkIn(Request $r){$s=$this->staff($r);$code=$r->validate(['ticket_code'=>'required|string|max:255'])['ticket_code'];$row=$this->ticketRow($s,$code);if(!$row)return response()->json(['success'=>false,'message'=>'Invalid ticket.'],404);if($row->ticket_status==='used'||$row->checked_in_at)return response()->json(['success'=>false,'message'=>'Ticket has already been used.'],409);if($row->payment_status!=='paid')return response()->json(['success'=>false,'message'=>'Booking payment is not confirmed.'],422);DB::transaction(function()use($row,$s){DB::table('booking_passengers')->where('id',$row->booking_passenger_id)->update(['checked_in_at'=>now(),'checked_in_by_staff_id'=>$s->id,'updated_at'=>now()]);DB::table('tickets')->where('id',$row->ticket_id)->update(['status'=>'used','used_at'=>now(),'updated_at'=>now()]);});return ['success'=>true,'message'=>'Passenger checked in.'];}
 private function ticketRow($s,$code){return DB::table('tickets')->join('booking_passengers','booking_passengers.id','=','tickets.booking_passenger_id')->join('bookings','bookings.id','=','tickets.booking_id')->join('trips','trips.id','=','bookings.trip_id')->join('buses','buses.id','=','trips.bus_id')->where('tickets.ticket_code',$code)->where('trips.operator_id',$s->operator_id)->where(function($q)use($s){$q->where('trips.driver_id',$s->id)->orWhere('trips.conductor_id',$s->id);})->select('tickets.id as ticket_id','tickets.status as ticket_status','booking_passengers.id as booking_passenger_id','booking_passengers.passenger_name','booking_passengers.nic','booking_passengers.seat_number','booking_passengers.checked_in_at','bookings.booking_reference','bookings.payment_status','bookings.status as booking_status','trips.trip_code','trips.status as trip_status','buses.bus_number')->first();}
 private function ticketPayload($x){return ['passenger_name'=>$x->passenger_name,'nic'=>$x->nic,'seat_number'=>$x->seat_number,'booking_reference'=>$x->booking_reference,'payment_status'=>$x->payment_status,'trip_code'=>$x->trip_code,'bus_number'=>$x->bus_number,'checked_in'=>$x->checked_in_at!==null||$x->ticket_status==='used'];}
}
